/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ScreenerRouteImport } from './routes/screener'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisTickerRouteImport } from './routes/analysis.$ticker'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenerRoute = ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisTickerRoute = AnalysisTickerRouteImport.update({
  id: '/analysis/$ticker',
  path: '/analysis/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/screener': typeof ScreenerRoute
  '/watchlist': typeof WatchlistRoute
  '/analysis/$ticker': typeof AnalysisTickerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/screener': typeof ScreenerRoute
  '/watchlist': typeof WatchlistRoute
  '/analysis/$ticker': typeof AnalysisTickerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/screener': typeof ScreenerRoute
  '/watchlist': typeof WatchlistRoute
  '/analysis/$ticker': typeof AnalysisTickerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/screener'
    | '/watchlist'
    | '/analysis/$ticker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calculator' | '/screener' | '/watchlist' | '/analysis/$ticker'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/screener'
    | '/watchlist'
    | '/analysis/$ticker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  ScreenerRoute: typeof ScreenerRoute
  WatchlistRoute: typeof WatchlistRoute
  AnalysisTickerRoute: typeof AnalysisTickerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screener': {
      id: '/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof ScreenerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$ticker': {
      id: '/analysis/$ticker'
      path: '/analysis/$ticker'
      fullPath: '/analysis/$ticker'
      preLoaderRoute: typeof AnalysisTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  ScreenerRoute: ScreenerRoute,
  WatchlistRoute: WatchlistRoute,
  AnalysisTickerRoute: AnalysisTickerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
